version: '3'
services:
  silvernobara:
    privileged: true
    image: silvernobara:latest
    security_opt:
      - label:disable
    build:
      dockerfile: Dockerfile
    volumes:
      - /mnt/user/appdata/letsencrypt/www/ostree:/repo
    network_mode: "host"
